version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypass
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 2G
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
